In [1]:
import pandas as pd
import numpy as np

In [2]:

data19=pd.read_csv('2019.csv')
data18=pd.read_csv('2018.csv')
data17=pd.read_csv('2017.csv')
data16=pd.read_csv('2016.csv')
data15=pd.read_csv('2015.csv')
data20=pd.read_csv('2020.csv')

In [3]:
data20.drop(data20.columns.difference(['Country name','Ladder score','Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices','Explained by: Generosity','Explained by: Perceptions of corruption']), 1, inplace=True)

In [4]:
data20.rename(columns = {'Ladder score':'Score'}, inplace = True)

In [5]:
data20

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101
...,...,...,...,...,...,...,...,...
148,Central African Republic,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265
149,Rwanda,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542
150,Zimbabwe,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929
151,South Sudan,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157
152,Afghanistan,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226

In [6]:
data20['year']='2020'

In [7]:
data20

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,year
0,Finland,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2020
1,Denmark,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2020
2,Switzerland,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2020
3,Iceland,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2020
4,Norway,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2020
...,...,...,...,...,...,...,...,...,...
148,Central African Republic,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2020
149,Rwanda,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,2020
150,Zimbabwe,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,2020
151,South Sudan,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,2020
152,Afghanistan,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,2020

In [8]:
gdpname='Explained by: Log GDP per capita'
socialname='Explained by: Social support'
lifeexpectancyname='Explained by: Healthy life expectancy'
freedomname='Explained by: Freedom to make life choices'
generocityname='Explained by: Generosity'
corruptionname='Explained by: Perceptions of corruption'

In [9]:
data19.drop(data19.columns.difference(['Country or region','Score', 'GDP per capita', 'Social support', 'Healthy life expectancy','Freedom to make life choices','Generosity', 'Perceptions of corruption']), 1, inplace=True)

In [10]:
data19

,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...
151,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [11]:
data19.rename(columns = {'Country or region':'Country name', 'GDP per capita':gdpname, 'Social support':socialname, 'Healthy life expectancy':lifeexpectancyname, 'Freedom to make life choices':freedomname,'Generosity':generocityname,'Perceptions of corruption':corruptionname}, inplace = True) 
data19['year']='2019'

In [12]:
data19

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,year
0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019
...,...,...,...,...,...,...,...,...,...
151,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,2019
152,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,2019
153,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,2019
154,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,2019
155,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091,2019

In [13]:
data18.drop(data18.columns.difference(['Country or region','Score', 'GDP per capita', 'Social support', 'Healthy life expectancy','Freedom to make life choices','Generosity', 'Perceptions of corruption']), 1, inplace=True)
data18.rename(columns = {'Country or region':'Country name', 'GDP per capita':gdpname, 'Social support':socialname, 'Healthy life expectancy':lifeexpectancyname, 'Freedom to make life choices':freedomname,'Generosity':generocityname,'Perceptions of corruption':corruptionname}, inplace = True) 
data18['year']='2018'

In [14]:
data18

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,year
0,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,2018
1,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,2018
2,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2018
3,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,2018
4,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,2018
...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064,2018
152,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097,2018
153,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106,2018
154,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038,2018
155,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076,2018

In [15]:
data17.drop(data17.columns.difference(['Country','Happiness.Score','Economy..GDP.per.Capita.','Family','Health..Life.Expectancy.','Freedom', 'Generosity', 'Trust..Government.Corruption.']), 1, inplace=True)
data17.rename(columns = {'Country':'Country name','Happiness.Score':'Score','Economy..GDP.per.Capita.':gdpname, 'Family':socialname,'Health..Life.Expectancy.':lifeexpectancyname, 'Freedom':freedomname, 'Generosity':generocityname,'Trust..Government.Corruption.':corruptionname }, inplace = True)
data17['year']='2017'

In [16]:
data17

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,year
0,Norway,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2017
1,Denmark,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2017
2,Iceland,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2017
3,Switzerland,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2017
4,Finland,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2017
...,...,...,...,...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,2017
151,Syria,3.462,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,2017
152,Tanzania,3.349,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,2017
153,Burundi,2.905,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,2017
154,Central African Republic,2.693,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2017

In [17]:
data16.drop(data16.columns.difference(['Country','Happiness Score','Economy (GDP per Capita)','Family','Health (Life Expectancy)','Freedom', 'Generosity', 'Trust (Government Corruption)']), 1, inplace=True)
data16.rename(columns = {'Country':'Country name','Happiness Score':'Score','Economy (GDP per Capita)':gdpname,'Family':socialname,'Health (Life Expectancy)':lifeexpectancyname,'Freedom':freedomname, 'Generosity':generocityname, 'Trust (Government Corruption)':corruptionname}, inplace = True)
data16['year']='2016'

In [18]:
data16

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Perceptions of corruption,Explained by: Generosity,year
0,Denmark,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2016
1,Switzerland,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2016
2,Iceland,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2016
3,Norway,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2016
4,Finland,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2016
...,...,...,...,...,...,...,...,...,...
152,Benin,3.484,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2016
153,Afghanistan,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2016
154,Togo,3.303,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2016
155,Syria,3.069,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,2016
156,Burundi,2.905,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2016

In [19]:
data15.drop(data15.columns.difference(['Country','Happiness Score','Economy (GDP per Capita)','Family','Health (Life Expectancy)','Freedom', 'Generosity', 'Trust (Government Corruption)']), 1, inplace=True)
data15.rename(columns = {'Country':'Country name','Happiness Score':'Score','Economy (GDP per Capita)':gdpname,'Family':socialname,'Health (Life Expectancy)':lifeexpectancyname,'Freedom':freedomname, 'Generosity':generocityname, 'Trust (Government Corruption)':corruptionname}, inplace = True)
data15['year']='2015'

In [20]:
data15.head()

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Perceptions of corruption,Explained by: Generosity,year
0,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [21]:
data15

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Perceptions of corruption,Explained by: Generosity,year
0,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015
...,...,...,...,...,...,...,...,...,...
153,Rwanda,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,2015
154,Benin,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,2015
155,Syria,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,2015
156,Burundi,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,2015
157,Togo,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,2015

In [22]:
data16

,Country name,Score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Perceptions of corruption,Explained by: Generosity,year
0,Denmark,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2016
1,Switzerland,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2016
2,Iceland,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2016
3,Norway,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2016
4,Finland,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2016
...,...,...,...,...,...,...,...,...,...
152,Benin,3.484,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2016
153,Afghanistan,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2016
154,Togo,3.303,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2016
155,Syria,3.069,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,2016
156,Burundi,2.905,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2016

In [23]:
frames = [data20, data19, data18, data17, data16, data15]

In [24]:
result = pd.concat(frames, sort=True)

In [25]:
result

,Country name,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Log GDP per capita,Explained by: Perceptions of corruption,Explained by: Social support,Score,year
0,Finland,0.662317,0.159670,0.961271,1.285190,0.477857,1.499526,7.8087,2020
1,Denmark,0.665040,0.242793,0.979333,1.326949,0.495260,1.503449,7.6456,2020
2,Switzerland,0.628954,0.269056,1.040533,1.390774,0.407946,1.472403,7.5599,2020
3,Iceland,0.661981,0.362330,1.000843,1.326502,0.144541,1.547567,7.5045,2020
4,Norway,0.670201,0.287985,1.008072,1.424207,0.434101,1.495173,7.4880,2020
...,...,...,...,...,...,...,...,...,...
153,Rwanda,0.592010,0.226280,0.428640,0.222080,0.551910,0.773700,3.4650,2015
154,Benin,0.484500,0.182600,0.319100,0.286650,0.080100,0.353860,3.3400,2015
155,Syria,0.156840,0.471790,0.721930,0.663200,0.189060,0.474890,3.0060,2015
156,Burundi,0.118500,0.197270,0.223960,0.015300,0.100620,0.415870,2.9050,2015
157,Togo,0.364530,0.166810,0.284430,0.208680,0.107310,0.139950,2.8390,2015

In [26]:
result=result.interpolate()

In [27]:
result

,Country name,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Log GDP per capita,Explained by: Perceptions of corruption,Explained by: Social support,Score,year
0,Finland,0.662317,0.159670,0.961271,1.285190,0.477857,1.499526,7.8087,2020
1,Denmark,0.665040,0.242793,0.979333,1.326949,0.495260,1.503449,7.6456,2020
2,Switzerland,0.628954,0.269056,1.040533,1.390774,0.407946,1.472403,7.5599,2020
3,Iceland,0.661981,0.362330,1.000843,1.326502,0.144541,1.547567,7.5045,2020
4,Norway,0.670201,0.287985,1.008072,1.424207,0.434101,1.495173,7.4880,2020
...,...,...,...,...,...,...,...,...,...
153,Rwanda,0.592010,0.226280,0.428640,0.222080,0.551910,0.773700,3.4650,2015
154,Benin,0.484500,0.182600,0.319100,0.286650,0.080100,0.353860,3.3400,2015
155,Syria,0.156840,0.471790,0.721930,0.663200,0.189060,0.474890,3.0060,2015
156,Burundi,0.118500,0.197270,0.223960,0.015300,0.100620,0.415870,2.9050,2015
157,Togo,0.364530,0.166810,0.284430,0.208680,0.107310,0.139950,2.8390,2015

In [28]:
import country_converter as coco

In [29]:
result['Country name'].unique()

array(['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Norway',
       'Netherlands', 'Sweden', 'New Zealand', 'Austria', 'Luxembourg',
       'Canada', 'Australia', 'United Kingdom', 'Israel', 'Costa Rica',
       'Ireland', 'Germany', 'United States', 'Czech Republic', 'Belgium',
       'United Arab Emirates', 'Malta', 'France', 'Mexico',
       'Taiwan Province of China', 'Uruguay', 'Saudi Arabia', 'Spain',
       'Guatemala', 'Italy', 'Singapore', 'Brazil', 'Slovenia',
       'El Salvador', 'Kosovo', 'Panama', 'Slovakia', 'Uzbekistan',
       'Chile', 'Bahrain', 'Lithuania', 'Trinidad and Tobago', 'Poland',
       'Colombia', 'Cyprus', 'Nicaragua', 'Romania', 'Kuwait',
       'Mauritius', 'Kazakhstan', 'Estonia', 'Philippines', 'Hungary',
       'Thailand', 'Argentina', 'Honduras', 'Latvia', 'Ecuador',
       'Portugal', 'Jamaica', 'South Korea', 'Japan', 'Peru', 'Serbia',
       'Bolivia', 'Pakistan', 'Paraguay', 'Dominican Republic',
       'Bosnia and Herzegovina', 'Moldova', 'Tajikistan', 'Montenegro',
       'Russia', 'Kyrgyzstan', 'Belarus', 'North Cyprus', 'Greece',
       'Hong Kong S.A.R. of China', 'Croatia', 'Libya', 'Mongolia',
       'Malaysia', 'Vietnam', 'Indonesia', 'Ivory Coast', 'Benin',
       'Maldives', 'Congo (Brazzaville)', 'Azerbaijan', 'Macedonia',
       'Ghana', 'Nepal', 'Turkey', 'China', 'Turkmenistan', 'Bulgaria',
       'Morocco', 'Cameroon', 'Venezuela', 'Algeria', 'Senegal', 'Guinea',
       'Niger', 'Laos', 'Albania', 'Cambodia', 'Bangladesh', 'Gabon',
       'South Africa', 'Iraq', 'Lebanon', 'Burkina Faso', 'Gambia',
       'Mali', 'Nigeria', 'Armenia', 'Georgia', 'Iran', 'Jordan',
       'Mozambique', 'Kenya', 'Namibia', 'Ukraine', 'Liberia',
       'Palestinian Territories', 'Uganda', 'Chad', 'Tunisia',
       'Mauritania', 'Sri Lanka', 'Congo (Kinshasa)', 'Swaziland',
       'Myanmar', 'Comoros', 'Togo', 'Ethiopia', 'Madagascar', 'Egypt',
       'Sierra Leone', 'Burundi', 'Zambia', 'Haiti', 'Lesotho', 'India',
       'Malawi', 'Yemen', 'Botswana', 'Tanzania',
       'Central African Republic', 'Rwanda', 'Zimbabwe', 'South Sudan',
       'Afghanistan', 'Taiwan', 'Qatar', 'Trinidad & Tobago',
       'Northern Cyprus', 'Hong Kong', 'North Macedonia', 'Bhutan',
       'Somalia', 'Syria', 'Belize', 'Sudan', 'Angola',
       'Hong Kong S.A.R., China', 'Puerto Rico', 'Suriname',
       'Somaliland Region', 'Oman', 'Somaliland region', 'Djibouti'],
      dtype=object)

In [ ]:
iso3_codes = coco.convert(names=result['Country name'].unique(), to='ISO3')

In [31]:
result

,Country name,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Log GDP per capita,Explained by: Perceptions of corruption,Explained by: Social support,Score,year
0,Finland,0.662317,0.159670,0.961271,1.285190,0.477857,1.499526,7.8087,2020
1,Denmark,0.665040,0.242793,0.979333,1.326949,0.495260,1.503449,7.6456,2020
2,Switzerland,0.628954,0.269056,1.040533,1.390774,0.407946,1.472403,7.5599,2020
3,Iceland,0.661981,0.362330,1.000843,1.326502,0.144541,1.547567,7.5045,2020
4,Norway,0.670201,0.287985,1.008072,1.424207,0.434101,1.495173,7.4880,2020
...,...,...,...,...,...,...,...,...,...
153,Rwanda,0.592010,0.226280,0.428640,0.222080,0.551910,0.773700,3.4650,2015
154,Benin,0.484500,0.182600,0.319100,0.286650,0.080100,0.353860,3.3400,2015
155,Syria,0.156840,0.471790,0.721930,0.663200,0.189060,0.474890,3.0060,2015
156,Burundi,0.118500,0.197270,0.223960,0.015300,0.100620,0.415870,2.9050,2015
157,Togo,0.364530,0.166810,0.284430,0.208680,0.107310,0.139950,2.8390,2015

In [32]:
result['code'] = result['Country name'].apply(coco.convert)

In [33]:
result

,Country name,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Log GDP per capita,Explained by: Perceptions of corruption,Explained by: Social support,Score,year,code
0,Finland,0.662317,0.159670,0.961271,1.285190,0.477857,1.499526,7.8087,2020,FIN
1,Denmark,0.665040,0.242793,0.979333,1.326949,0.495260,1.503449,7.6456,2020,DNK
2,Switzerland,0.628954,0.269056,1.040533,1.390774,0.407946,1.472403,7.5599,2020,CHE
3,Iceland,0.661981,0.362330,1.000843,1.326502,0.144541,1.547567,7.5045,2020,ISL
4,Norway,0.670201,0.287985,1.008072,1.424207,0.434101,1.495173,7.4880,2020,NOR
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,0.592010,0.226280,0.428640,0.222080,0.551910,0.773700,3.4650,2015,RWA
154,Benin,0.484500,0.182600,0.319100,0.286650,0.080100,0.353860,3.3400,2015,BEN
155,Syria,0.156840,0.471790,0.721930,0.663200,0.189060,0.474890,3.0060,2015,SYR
156,Burundi,0.118500,0.197270,0.223960,0.015300,0.100620,0.415870,2.9050,2015,BDI
157,Togo,0.364530,0.166810,0.284430,0.208680,0.107310,0.139950,2.8390,2015,TGO

In [34]:
result=result.replace(0,np.nan)

In [35]:
result=result.interpolate()

In [36]:
result

,Country name,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Healthy life expectancy,Explained by: Log GDP per capita,Explained by: Perceptions of corruption,Explained by: Social support,Score,year,code
0,Finland,0.662317,0.159670,0.961271,1.285190,0.477857,1.499526,7.8087,2020,FIN
1,Denmark,0.665040,0.242793,0.979333,1.326949,0.495260,1.503449,7.6456,2020,DNK
2,Switzerland,0.628954,0.269056,1.040533,1.390774,0.407946,1.472403,7.5599,2020,CHE
3,Iceland,0.661981,0.362330,1.000843,1.326502,0.144541,1.547567,7.5045,2020,ISL
4,Norway,0.670201,0.287985,1.008072,1.424207,0.434101,1.495173,7.4880,2020,NOR
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,0.592010,0.226280,0.428640,0.222080,0.551910,0.773700,3.4650,2015,RWA
154,Benin,0.484500,0.182600,0.319100,0.286650,0.080100,0.353860,3.3400,2015,BEN
155,Syria,0.156840,0.471790,0.721930,0.663200,0.189060,0.474890,3.0060,2015,SYR
156,Burundi,0.118500,0.197270,0.223960,0.015300,0.100620,0.415870,2.9050,2015,BDI
157,Togo,0.364530,0.166810,0.284430,0.208680,0.107310,0.139950,2.8390,2015,TGO

In [37]:
result=result.replace(0,np.nan)

In [38]:
result=result.interpolate()

In [39]:
#result.to_csv(r'D:\WHI\Full Data.csv')